name: 오늘 급식 메뉴는 뭔가요?
on:
  schedule:
    - cron: '0 0 ? * MON-FRI' # KST 기준 월-금 오전 9시
  workflow_dispatch:

jobs:
  daily-menu:
    uses: ./.github/workflows/get-menu.yml
    with:
      MENU_FREQUENCY: 'DAILY'
    secrets: inherit
