name: 오늘 급식 메뉴는 뭔가요?
on:
  schedule:
    - cron: '30 1 ? * MON-FRI' # KST 기준 월 오전 10시 30분
  workflow_dispatch:

jobs:
  daily-lunch-menu:
    runs-on: ubuntu-latest
    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Python 환경 설정
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      # 3. 필요한 라이브러리 설치
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 4. 실행
      - name: Run
        env:
          MENU_FREQUENCY: 'DAILY'
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: python main.py
