name: 오늘 급식 메뉴는 뭔가요? (점심)
on:
  schedule:
    - cron: '30 1 ? * MON-FRI' # KST 기준 월 오전 10시 30분
  workflow_dispatch:

jobs:
  daily-lunch-menu:
    uses: ./.github/workflows/get-menu.yml@main
    with:
      MENU_FREQUENCY: 'DAILY_LUNCH'
    secrets: inherit
