name: 메뉴 가져오기
on:
  workflow_call:
    inputs:
      MENU_FREQUENCY:
        required: false
        type: string
      RESTAURANT:
        required: false
        type: string

jobs:
  get-menu:
    runs-on: ubuntu-latest
    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 실행
      - name: Run Docker Compose
        env:
          MENU_FREQUENCY: ${{ inputs.MENU_FREQUENCY }}
          RESTAURANT: ${{ inputs.RESTAURANT }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          VPN_CONFIG_BASE64: ${{ secrets.VPN_CONFIG_BASE64 }}
          VPN_USER: ${{ secrets.VPN_USER }}
          VPN_PASS: ${{ secrets.VPN_PASS }}
        run: docker compose up
