name: 이번주 급식 메뉴는 뭔가요?
on:
  schedule:
    - cron: '0 1 ? * MON' # KST 기준 월-금 오전 10시
  workflow_dispatch:

jobs:
  weekly-menu:
    uses: ./.github/workflows/get-menu.yml@main
    with:
      MENU_FREQUENCY: 'WEEKLY'
    secrets: inherit
